/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package octavian.encrypter;

import java.io.File;
import javax.swing.JFileChooser;
import octavian.ui.AboutFrame;
import octavian.ui.DocumentationFrame;
import octavian.ui.EmailFrame;
import octavian.ui.KeyBoardShortcutsFrame;
import octavian.ui.SettingsFrame;

/**
 *
 * @author octavian.bodnariu
 */
public class MainApplication extends javax.swing.JFrame {

//<editor-fold defaultstate="collapsed" desc="User Variables">
   private JFileChooser filechoser;
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Constructors">   
   /**
     * Creates new form MainApplication
     */
    public MainApplication() {
        initComponents();
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        AlgorithmsList_ComboBox = new javax.swing.JComboBox<>();
        jLabel_SelectAlgorithm = new javax.swing.JLabel();
        encrypt_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        generatePDF_Report_CheckBox = new javax.swing.JCheckBox();
        generateLogs_CheckBox = new javax.swing.JCheckBox();
        decrypt_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        email_textField = new javax.swing.JTextField();
        eraseSourceFile_CheckBox = new javax.swing.JCheckBox();
        pathToFile_TextField = new javax.swing.JTextField();
        selectFile_button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        console_textArea = new javax.swing.JTextArea();
        jLabel_Console = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        about_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        BrowseFilesMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        DocumentationMenuItem = new javax.swing.JMenuItem();
        KeyboardShortcut = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        AboutMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File encrypter");
        setResizable(false);

        AlgorithmsList_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RSA", "Rabin", "El Gamal", "Goldwasser-Micali" }));
        AlgorithmsList_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgorithmsList_ComboBoxActionPerformed(evt);
            }
        });

        jLabel_SelectAlgorithm.setText("Select Algorithm :");

        encrypt_button.setText("Encrypt");
        encrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_buttonActionPerformed(evt);
            }
        });

        generatePDF_Report_CheckBox.setText("Generate PDF Report");

        generateLogs_CheckBox.setText("Generate Logs");

        decrypt_button.setText("Decrypt");
        decrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypt_buttonActionPerformed(evt);
            }
        });

        exit_button.setText("Exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        eraseSourceFile_CheckBox.setText("Erase Source File");

        selectFile_button.setText("Browse");
        selectFile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFile_buttonActionPerformed(evt);
            }
        });

        console_textArea.setEditable(false);
        console_textArea.setBackground(new java.awt.Color(0, 0, 0));
        console_textArea.setColumns(20);
        console_textArea.setForeground(new java.awt.Color(51, 255, 51));
        console_textArea.setRows(5);
        console_textArea.setText("[INFO]Application started with success !");
        jScrollPane1.setViewportView(console_textArea);

        jLabel_Console.setText("Console");

        about_button.setText("About");
        about_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Note : If is empty the application will generate a new set of keys");

        jButton1.setText("Key File");

        jMenu3.setText("File");

        BrowseFilesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        BrowseFilesMenuItem.setText("Browse Files");
        BrowseFilesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFilesMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(BrowseFilesMenuItem);

        ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ExitMenuItem);

        jMenuBar2.add(jMenu3);

        jMenu6.setText("Help");

        DocumentationMenuItem.setText("Documentation");
        DocumentationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentationMenuItemActionPerformed(evt);
            }
        });
        jMenu6.add(DocumentationMenuItem);

        KeyboardShortcut.setText("Keyboard Shorcuts");
        KeyboardShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyboardShortcutActionPerformed(evt);
            }
        });
        jMenu6.add(KeyboardShortcut);
        jMenu6.add(jSeparator2);

        AboutMenuItem.setText("About");
        AboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        jMenu6.add(AboutMenuItem);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encrypt_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decrypt_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(about_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generatePDF_Report_CheckBox)
                                .addGap(39, 39, 39)
                                .addComponent(eraseSourceFile_CheckBox)
                                .addGap(36, 36, 36)
                                .addComponent(generateLogs_CheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_SelectAlgorithm)
                                .addGap(18, 18, 18)
                                .addComponent(AlgorithmsList_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectFile_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pathToFile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Console)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlgorithmsList_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_SelectAlgorithm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathToFile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFile_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatePDF_Report_CheckBox)
                    .addComponent(eraseSourceFile_CheckBox)
                    .addComponent(generateLogs_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Console)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button)
                    .addComponent(decrypt_button)
                    .addComponent(about_button)
                    .addComponent(exit_button))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
////<editor-fold defaultstate="collapsed" desc="Private Functions">
    private void encrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_buttonActionPerformed
        // TODO add your handling code here:
        
        if(generatePDF_Report_CheckBox.isSelected())
        {
            //Genereaza raport PDF
        }
        
        if(generateLogs_CheckBox.isSelected())
        {
            //Genereaza logs.txt 
            //Se recomanda sa nu fie dezactivat
        }
        
        if(eraseSourceFile_CheckBox.isSelected())
        {
            //Sterge fisierul/folderul de input
        }
        
    }//GEN-LAST:event_encrypt_buttonActionPerformed

    private void AlgorithmsList_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgorithmsList_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlgorithmsList_ComboBoxActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    /**
     * Selectarea fisierului
     * @param evt 
     */
    private void selectFile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFile_buttonActionPerformed
        selectFileAction();
    }//GEN-LAST:event_selectFile_buttonActionPerformed

    private void KeyboardShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyboardShortcutActionPerformed
        showKeyboardShortcuts();
    }//GEN-LAST:event_KeyboardShortcutActionPerformed

    private void about_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_buttonActionPerformed
        showAbout();
    }//GEN-LAST:event_about_buttonActionPerformed

    private void decrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypt_buttonActionPerformed
        //decrypt();
    }//GEN-LAST:event_decrypt_buttonActionPerformed

    private void BrowseFilesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFilesMenuItemActionPerformed
       selectFileAction();
    }//GEN-LAST:event_BrowseFilesMenuItemActionPerformed

    private void AboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuItemActionPerformed
        showAbout();
    }//GEN-LAST:event_AboutMenuItemActionPerformed

    private void DocumentationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentationMenuItemActionPerformed
        documentationSelect();
    }//GEN-LAST:event_DocumentationMenuItemActionPerformed
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Main">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainApplication().setVisible(true);
        });
    }
    
    /**
     * Exiting the app
     */
    private void exit(){
        System.exit(0);
    }
    
    /**
     * Shows the about frame
     */
    private void showAbout(){
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.setVisible(true);
    }
    
    private void showKeyboardShortcuts(){
        KeyBoardShortcutsFrame kbsf = new KeyBoardShortcutsFrame();
        kbsf.setVisible(true);
    }
    
    private void selectFileAction(){
        File directory;
        filechoser = new JFileChooser();
        int returnVal;
        returnVal = filechoser.showOpenDialog(jLabel_SelectAlgorithm);
        filechoser.setVisible(true);
        directory = filechoser.getSelectedFile();
        pathToFile_TextField.setText(directory.getAbsolutePath());
    }
    
    private void emailSelect(){
        EmailFrame emailFrame = new EmailFrame();
        emailFrame.setVisible(true);
    }
    
    private void settingsSelect(){
        SettingsFrame settingsFrame = new SettingsFrame();
        settingsFrame.setVisible(true);
    }
    
    private void documentationSelect(){
        DocumentationFrame docFrame = new DocumentationFrame();
        docFrame.setVisible(true);
    }
//</editor-fold>

////<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JComboBox<String> AlgorithmsList_ComboBox;
    private javax.swing.JMenuItem BrowseFilesMenuItem;
    private javax.swing.JMenuItem DocumentationMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenuItem KeyboardShortcut;
    private javax.swing.JButton about_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea console_textArea;
    private javax.swing.JButton decrypt_button;
    private javax.swing.JTextField email_textField;
    private javax.swing.JButton encrypt_button;
    private javax.swing.JCheckBox eraseSourceFile_CheckBox;
    private javax.swing.JButton exit_button;
    private javax.swing.JCheckBox generateLogs_CheckBox;
    private javax.swing.JCheckBox generatePDF_Report_CheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Console;
    private javax.swing.JLabel jLabel_SelectAlgorithm;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField pathToFile_TextField;
    private javax.swing.JButton selectFile_button;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
