/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encrypter;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author octavian.bodnariu
 */
public class MainApplication extends javax.swing.JFrame {

//===================================VARIABILE===========================================================================================================================================================================
   private JFileChooser filechoser;
    /**
     * Creates new form MainApplication
     */
    public MainApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        AlgorithmsList_ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        encrypt_button = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        generatePDF_Report_CheckBox = new javax.swing.JCheckBox();
        generateLogs_CheckBox = new javax.swing.JCheckBox();
        storeKey_CheckBox = new javax.swing.JCheckBox();
        decrypt_button = new javax.swing.JButton();
        generatePassword_CheckBox = new javax.swing.JCheckBox();
        exit_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sendMail_CheckBox = new javax.swing.JCheckBox();
        email_textField = new javax.swing.JTextField();
        eraseSourceFile_CheckBox = new javax.swing.JCheckBox();
        pathToFile_TextField = new javax.swing.JTextField();
        selectFile_button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        console_textArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        signDigitaly_CheckBox = new javax.swing.JCheckBox();
        file_RadioButton = new javax.swing.JRadioButton();
        folder_RadioButton = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        outputFile_textField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        database_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        addExtension_CheckBox = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        exit_MenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File encrypter");
        setResizable(false);

        AlgorithmsList_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caesar", "El Gamal", "GoldWasser Micali", "Mars", "RSA", "Rabin" }));
        AlgorithmsList_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgorithmsList_ComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Algorithm :");

        encrypt_button.setText("Encrypt");
        encrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_buttonActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(255, 255, 51));

        generatePDF_Report_CheckBox.setText("Generate PDF Report");

        generateLogs_CheckBox.setText("Generate Logs");

        storeKey_CheckBox.setText("Store key in Database");

        decrypt_button.setText("Decrypt");

        generatePassword_CheckBox.setText("Generate Password");

        exit_button.setText("Exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Email : ");

        sendMail_CheckBox.setText("Send encrypted file ");

        email_textField.setText("someone@mail.com");

        eraseSourceFile_CheckBox.setText("Erase Source File");

        pathToFile_TextField.setText("Path to file");

        selectFile_button.setText("Select File");
        selectFile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFile_buttonActionPerformed(evt);
            }
        });

        console_textArea.setEditable(false);
        console_textArea.setBackground(new java.awt.Color(0, 0, 0));
        console_textArea.setColumns(20);
        console_textArea.setForeground(new java.awt.Color(51, 255, 51));
        console_textArea.setRows(5);
        console_textArea.setText("[INFO]Hi ! I am your text");
        jScrollPane1.setViewportView(console_textArea);

        jLabel2.setText("Console :");

        signDigitaly_CheckBox.setText("Sign Digitaly");

        file_RadioButton.setText("File");
        file_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_RadioButtonActionPerformed(evt);
            }
        });

        folder_RadioButton.setText("Folder");
        folder_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folder_RadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Output File : ");

        database_button.setText("Database");

        jLabel5.setText("Encrypt :");

        addExtension_CheckBox.setText("Add \".ss\" to crypted files");

        jMenu3.setText("File");

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Select File");
        jMenu3.add(jMenuItem12);

        exit_MenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit_MenuItem.setText("Exit");
        exit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_MenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(exit_MenuItem);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuItem1.setText("jMenuItem1");
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Profile");

        jMenuItem11.setText("Settings");
        jMenu5.add(jMenuItem11);

        jMenuItem2.setText("Email");
        jMenu5.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Database");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Show Logs");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Show History");
        jMenu5.add(jMenuItem5);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Help");

        jMenuItem6.setText("Documentation");
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("Keyboard Shorcuts");
        jMenu6.add(jMenuItem7);
        jMenu6.add(jSeparator2);

        jMenuItem8.setText("Report a Bug");
        jMenu6.add(jMenuItem8);

        jMenuItem10.setText("About");
        jMenu6.add(jMenuItem10);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generatePassword_CheckBox)
                            .addComponent(generateLogs_CheckBox)
                            .addComponent(generatePDF_Report_CheckBox))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signDigitaly_CheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eraseSourceFile_CheckBox)
                                .addGap(49, 49, 49)
                                .addComponent(addExtension_CheckBox))
                            .addComponent(storeKey_CheckBox))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)
                            .addComponent(jSeparator7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(AlgorithmsList_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outputFile_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(file_RadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(folder_RadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectFile_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pathToFile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator3)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendMail_CheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(encrypt_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decrypt_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(database_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exit_button)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlgorithmsList_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(outputFile_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathToFile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFile_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(file_RadioButton)
                    .addComponent(folder_RadioButton)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendMail_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatePDF_Report_CheckBox)
                    .addComponent(eraseSourceFile_CheckBox)
                    .addComponent(addExtension_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateLogs_CheckBox)
                    .addComponent(signDigitaly_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatePassword_CheckBox)
                    .addComponent(storeKey_CheckBox))
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button)
                    .addComponent(decrypt_button)
                    .addComponent(database_button)
                    .addComponent(exit_button))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//==================================FUNCTII PRIVATE=========================================================================================================================================
    private void encrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_buttonActionPerformed
        // TODO add your handling code here:
        if(addExtension_CheckBox.isSelected())
        {
            //Adauga extensie la fisierul output
        }
        
        if(generatePDF_Report_CheckBox.isSelected())
        {
            //Genereaza raport PDF
        }
        
        if(generateLogs_CheckBox.isSelected())
        {
            //Genereaza logs.txt 
            //Se recomanda sa nu fie dezactivat
        }
        
        if(generatePassword_CheckBox.isSelected())
        {
            //Genereaza parola ???
        }
        
        if(eraseSourceFile_CheckBox.isSelected())
        {
            //Sterge fisierul/folderul de input
        }
        
        if(signDigitaly_CheckBox.isSelected())
        {
            //Semneaza digital
        }
        
        if(storeKey_CheckBox.isSelected())
        {
            //Insereaza cheia in baza de date
        }
        
        if(sendMail_CheckBox.isSelected())
        {
            //Send email
            //Only gmail works
        }
        
    }//GEN-LAST:event_encrypt_buttonActionPerformed

    private void AlgorithmsList_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgorithmsList_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlgorithmsList_ComboBoxActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void exit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_MenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_MenuItemActionPerformed

    private void file_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_RadioButtonActionPerformed
        // TODO add your handling code here:
        file_RadioButton.setSelected(true);
        folder_RadioButton.setSelected(false);
    }//GEN-LAST:event_file_RadioButtonActionPerformed

    private void folder_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folder_RadioButtonActionPerformed
        // TODO add your handling code here:
        folder_RadioButton.setSelected(true);
        file_RadioButton.setSelected(false);
    }//GEN-LAST:event_folder_RadioButtonActionPerformed

    private void selectFile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFile_buttonActionPerformed
        // TODO add your handling code here:
        File directory;
        filechoser = new JFileChooser();
        int returnVal = filechoser.showOpenDialog(jLabel1);
        filechoser.setVisible(true);
        directory = filechoser.getCurrentDirectory();
        pathToFile_TextField.setText(directory.getPath());
        //System.out.println("Works");
        
    }//GEN-LAST:event_selectFile_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApplication().setVisible(true);
            }
        });
    }

//====================================VARIABILE PRIVATE(GUI)=====================================================================================================================================================================    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlgorithmsList_ComboBox;
    private javax.swing.JCheckBox addExtension_CheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea console_textArea;
    private javax.swing.JButton database_button;
    private javax.swing.JButton decrypt_button;
    private javax.swing.JTextField email_textField;
    private javax.swing.JButton encrypt_button;
    private javax.swing.JCheckBox eraseSourceFile_CheckBox;
    private javax.swing.JMenuItem exit_MenuItem;
    private javax.swing.JButton exit_button;
    private javax.swing.JRadioButton file_RadioButton;
    private javax.swing.JRadioButton folder_RadioButton;
    private javax.swing.JCheckBox generateLogs_CheckBox;
    private javax.swing.JCheckBox generatePDF_Report_CheckBox;
    private javax.swing.JCheckBox generatePassword_CheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField outputFile_textField;
    private javax.swing.JTextField pathToFile_TextField;
    private javax.swing.JButton selectFile_button;
    private javax.swing.JCheckBox sendMail_CheckBox;
    private javax.swing.JCheckBox signDigitaly_CheckBox;
    private javax.swing.JCheckBox storeKey_CheckBox;
    // End of variables declaration//GEN-END:variables
}
